from dataclasses import dataclass

VERBOSE_NAME_FIELD = 'название'
VERBOSE_RECIPE_FIELD = 'рецепт'
VERBOSE_INGREDIENT_FIELD = 'ингредиент'
VERBOSE_SLUG_FIELD = 'идентификатор'

MAX_USER_FIRST_LAST_NAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254
MAX_INGREDIENT_NAME_LENGTH = 128
MAX_MEASUREMENT_UNIT_LENGTH = 64
MAX_TAG_NAME_LENGTH = 32
MAX_SLUG_LENGTH = 32
MAX_RECIPE_NAME_LENGTH = 256
MIN_COOKING_TIME_VALUE = 1
DEFAULT_MODEL_ADMIN_NAME_LENGTH = 60
DEFAULT_MODEL_ADMIN_NAME_SUFFIX = '...'

LOOKUP_DIGIT_PATTERN = r'\d+'
SHORT_LINK_TOKEN_NBYTES = 4
SHORT_LINK_URL_PATH = 's/'
SMALL_INTEGER_FIELD_MAX_VALUE = 32767

FRONTEND_RECIPES_PATH = 'recipes/'


@dataclass(frozen=True)
class HttpMethod:
    GET = 'get'
    POST = 'post'
    DELETE = 'delete'
    PUT = 'put'
    PATCH = 'patch'
    HEAD = 'head'
    OPTIONS = 'options'
