# Generated by Django 4.2.16 on 2024-10-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'ингродиент', 'verbose_name_plural': 'Ингродиенты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
