# Generated by Django 4.2.16 on 2024-10-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_recipeshortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_token', to='foodgram.recipe'),
        ),
    ]
