# Generated by Django 4.2.16 on 2024-10-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_alter_recipeshortlink_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='token',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
