# Generated by Django 4.2.16 on 2024-10-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_remove_tag_recipes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='IngredientRecipe',
        ),
    ]
