# Generated by Django 4.2.16 on 2024-10-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_recipeingredient_rename_tagrecipe_recipetag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.ingredient'),
        ),
    ]
