MAX_INGREDIENT_NAME_LENGTH = 128
MAX_MEASUREMENT_UNIT_LENGTH = 64
MAX_TAG_NAME_LENGTH = 32
MAX_TAG_SLUG_LENGTH = 32
MAX_RECIPE_NAME_LENGTH = 256
DEFAULT_MODEL_ADMIN_NAME_LENGTH = 60
DEFAULT_MODEL_ADMIN_NAME_SUFFIX = '...'
