# Generated by Django 4.2.16 on 2024-10-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='test',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(('user__exact', models.F('author')), _negated=True), name='test'),
        ),
    ]
