# Generated by Django 4.2.16 on 2024-10-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_subscriptions_test_subscriptions_test'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='test',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(('user__exact', models.F('author')), _negated=True), name='user_cant_follow_on_self'),
        ),
    ]
